In [1]:
import pandas as pd
df = pd.read_csv('Downloads/mobile_sales_data_2025.csv')
print(df)

     Sale_ID     Brand              Model    Country Storage   Color  \
0          1    Realme     Realme Model 2         UK   512GB    Gold
1          2      Vivo      Vivo Model 20  Australia   512GB    Blue
2          3  Motorola  Motorola Model 12    Germany   512GB   White
3          4      Vivo      Vivo Model 13        USA   512GB    Gold
4          5      Vivo      Vivo Model 15        UAE   128GB  Silver
..       ...       ...                ...        ...     ...     ...
495      496   OnePlus    OnePlus Model 5         UK   128GB    Blue
496      497    Xiaomi     Xiaomi Model 4     Canada   128GB    Gold
497      498      Vivo       Vivo Model 9   Pakistan   256GB    Blue
498      499   Samsung   Samsung Model 19     France   128GB    Gold
499      500    Xiaomi    Xiaomi Model 14         UK    64GB    Gold

     Price_USD  Units_Sold  Revenue_USD  Customer_Rating  Payment_Method  \
0          656          20        13120              3.7    Installments
1         1013           9         9117              3.7      Debit Card
2         1471           7        10297              3.1     Credit Card
3         1220          19        23180              3.6      Debit Card
4          375           8         3000              4.4  Online Payment
..         ...         ...          ...              ...             ...
495        371          10         3710              3.5      Debit Card
496        414           8         3312              5.0    Installments
497        314          17         5338              4.6            Cash
498        342           1          342              4.5            Cash
499       1457           4         5828              3.2    Installments

     Sale_Month  Sale_Year
0            11       2025
1             2       2025
2             2       2025
3             6       2025
4             1       2025
..          ...        ...
495           6       2025
496           7       2025
497           7       2025
498           6       2025
499           9       2025

[500 rows x 13 columns]

In [2]:
df.head()

,Sale_ID,Brand,Model,Country,Storage,Color,Price_USD,Units_Sold,Revenue_USD,Customer_Rating,Payment_Method,Sale_Month,Sale_Year
0,1,Realme,Realme Model 2,UK,512GB,Gold,656,20,13120,3.7,Installments,11,2025
1,2,Vivo,Vivo Model 20,Australia,512GB,Blue,1013,9,9117,3.7,Debit Card,2,2025
2,3,Motorola,Motorola Model 12,Germany,512GB,White,1471,7,10297,3.1,Credit Card,2,2025
3,4,Vivo,Vivo Model 13,USA,512GB,Gold,1220,19,23180,3.6,Debit Card,6,2025
4,5,Vivo,Vivo Model 15,UAE,128GB,Silver,375,8,3000,4.4,Online Payment,1,2025

In [3]:
df.tail()

,Sale_ID,Brand,Model,Country,Storage,Color,Price_USD,Units_Sold,Revenue_USD,Customer_Rating,Payment_Method,Sale_Month,Sale_Year
495,496,OnePlus,OnePlus Model 5,UK,128GB,Blue,371,10,3710,3.5,Debit Card,6,2025
496,497,Xiaomi,Xiaomi Model 4,Canada,128GB,Gold,414,8,3312,5.0,Installments,7,2025
497,498,Vivo,Vivo Model 9,Pakistan,256GB,Blue,314,17,5338,4.6,Cash,7,2025
498,499,Samsung,Samsung Model 19,France,128GB,Gold,342,1,342,4.5,Cash,6,2025
499,500,Xiaomi,Xiaomi Model 14,UK,64GB,Gold,1457,4,5828,3.2,Installments,9,2025

In [6]:
df.drop_duplicates()

,Sale_ID,Brand,Model,Country,Storage,Color,Price_USD,Units_Sold,Revenue_USD,Customer_Rating,Payment_Method,Sale_Month,Sale_Year
0,1,Realme,Realme Model 2,UK,512GB,Gold,656,20,13120,3.7,Installments,11,2025
1,2,Vivo,Vivo Model 20,Australia,512GB,Blue,1013,9,9117,3.7,Debit Card,2,2025
2,3,Motorola,Motorola Model 12,Germany,512GB,White,1471,7,10297,3.1,Credit Card,2,2025
3,4,Vivo,Vivo Model 13,USA,512GB,Gold,1220,19,23180,3.6,Debit Card,6,2025
4,5,Vivo,Vivo Model 15,UAE,128GB,Silver,375,8,3000,4.4,Online Payment,1,2025
...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,496,OnePlus,OnePlus Model 5,UK,128GB,Blue,371,10,3710,3.5,Debit Card,6,2025
496,497,Xiaomi,Xiaomi Model 4,Canada,128GB,Gold,414,8,3312,5.0,Installments,7,2025
497,498,Vivo,Vivo Model 9,Pakistan,256GB,Blue,314,17,5338,4.6,Cash,7,2025
498,499,Samsung,Samsung Model 19,France,128GB,Gold,342,1,342,4.5,Cash,6,2025
499,500,Xiaomi,Xiaomi Model 14,UK,64GB,Gold,1457,4,5828,3.2,Installments,9,2025

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 13 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Sale_ID          500 non-null    int64
 1   Brand            500 non-null    object
 2   Model            500 non-null    object
 3   Country          500 non-null    object
 4   Storage          500 non-null    object
 5   Color            500 non-null    object
 6   Price_USD        500 non-null    int64
 7   Units_Sold       500 non-null    int64
 8   Revenue_USD      500 non-null    int64
 9   Customer_Rating  500 non-null    float64
 10  Payment_Method   500 non-null    object
 11  Sale_Month       500 non-null    int64
 12  Sale_Year        500 non-null    int64
dtypes: float64(1), int64(6), object(6)
memory usage: 50.9+ KB

In [9]:
print(df.shape)

(500, 13)

In [11]:
# Add the Cost_USD column
df['Cost_USD'] = df['Revenue_USD'] * 0.6
print(df)

     Sale_ID     Brand              Model    Country Storage   Color  \
0          1    Realme     Realme Model 2         UK   512GB    Gold
1          2      Vivo      Vivo Model 20  Australia   512GB    Blue
2          3  Motorola  Motorola Model 12    Germany   512GB   White
3          4      Vivo      Vivo Model 13        USA   512GB    Gold
4          5      Vivo      Vivo Model 15        UAE   128GB  Silver
..       ...       ...                ...        ...     ...     ...
495      496   OnePlus    OnePlus Model 5         UK   128GB    Blue
496      497    Xiaomi     Xiaomi Model 4     Canada   128GB    Gold
497      498      Vivo       Vivo Model 9   Pakistan   256GB    Blue
498      499   Samsung   Samsung Model 19     France   128GB    Gold
499      500    Xiaomi    Xiaomi Model 14         UK    64GB    Gold

     Price_USD  Units_Sold  Revenue_USD  Customer_Rating  Payment_Method  \
0          656          20        13120              3.7    Installments
1         1013           9         9117              3.7      Debit Card
2         1471           7        10297              3.1     Credit Card
3         1220          19        23180              3.6      Debit Card
4          375           8         3000              4.4  Online Payment
..         ...         ...          ...              ...             ...
495        371          10         3710              3.5      Debit Card
496        414           8         3312              5.0    Installments
497        314          17         5338              4.6            Cash
498        342           1          342              4.5            Cash
499       1457           4         5828              3.2    Installments

     Sale_Month  Sale_Year  Cost_USD
0            11       2025    7872.0
1             2       2025    5470.2
2             2       2025    6178.2
3             6       2025   13908.0
4             1       2025    1800.0
..          ...        ...       ...
495           6       2025    2226.0
496           7       2025    1987.2
497           7       2025    3202.8
498           6       2025     205.2
499           9       2025    3496.8

[500 rows x 14 columns]

In [12]:
# Add the Profit_USD column
df['Profit_USD'] = df['Revenue_USD'] - df['Cost_USD']
print(df)

     Sale_ID     Brand              Model    Country Storage   Color  \
0          1    Realme     Realme Model 2         UK   512GB    Gold
1          2      Vivo      Vivo Model 20  Australia   512GB    Blue
2          3  Motorola  Motorola Model 12    Germany   512GB   White
3          4      Vivo      Vivo Model 13        USA   512GB    Gold
4          5      Vivo      Vivo Model 15        UAE   128GB  Silver
..       ...       ...                ...        ...     ...     ...
495      496   OnePlus    OnePlus Model 5         UK   128GB    Blue
496      497    Xiaomi     Xiaomi Model 4     Canada   128GB    Gold
497      498      Vivo       Vivo Model 9   Pakistan   256GB    Blue
498      499   Samsung   Samsung Model 19     France   128GB    Gold
499      500    Xiaomi    Xiaomi Model 14         UK    64GB    Gold

     Price_USD  Units_Sold  Revenue_USD  Customer_Rating  Payment_Method  \
0          656          20        13120              3.7    Installments
1         1013           9         9117              3.7      Debit Card
2         1471           7        10297              3.1     Credit Card
3         1220          19        23180              3.6      Debit Card
4          375           8         3000              4.4  Online Payment
..         ...         ...          ...              ...             ...
495        371          10         3710              3.5      Debit Card
496        414           8         3312              5.0    Installments
497        314          17         5338              4.6            Cash
498        342           1          342              4.5            Cash
499       1457           4         5828              3.2    Installments

     Sale_Month  Sale_Year  Cost_USD  Profit_USD
0            11       2025    7872.0      5248.0
1             2       2025    5470.2      3646.8
2             2       2025    6178.2      4118.8
3             6       2025   13908.0      9272.0
4             1       2025    1800.0      1200.0
..          ...        ...       ...         ...
495           6       2025    2226.0      1484.0
496           7       2025    1987.2      1324.8
497           7       2025    3202.8      2135.2
498           6       2025     205.2       136.8
499           9       2025    3496.8      2331.2

[500 rows x 15 columns]

In [13]:
# Add the Profit_Margin column
df['Profit_Margin'] = (df['Profit_USD'] / df['Revenue_USD']) * 100
print(df)

     Sale_ID     Brand              Model    Country Storage   Color  \
0          1    Realme     Realme Model 2         UK   512GB    Gold
1          2      Vivo      Vivo Model 20  Australia   512GB    Blue
2          3  Motorola  Motorola Model 12    Germany   512GB   White
3          4      Vivo      Vivo Model 13        USA   512GB    Gold
4          5      Vivo      Vivo Model 15        UAE   128GB  Silver
..       ...       ...                ...        ...     ...     ...
495      496   OnePlus    OnePlus Model 5         UK   128GB    Blue
496      497    Xiaomi     Xiaomi Model 4     Canada   128GB    Gold
497      498      Vivo       Vivo Model 9   Pakistan   256GB    Blue
498      499   Samsung   Samsung Model 19     France   128GB    Gold
499      500    Xiaomi    Xiaomi Model 14         UK    64GB    Gold

     Price_USD  Units_Sold  Revenue_USD  Customer_Rating  Payment_Method  \
0          656          20        13120              3.7    Installments
1         1013           9         9117              3.7      Debit Card
2         1471           7        10297              3.1     Credit Card
3         1220          19        23180              3.6      Debit Card
4          375           8         3000              4.4  Online Payment
..         ...         ...          ...              ...             ...
495        371          10         3710              3.5      Debit Card
496        414           8         3312              5.0    Installments
497        314          17         5338              4.6            Cash
498        342           1          342              4.5            Cash
499       1457           4         5828              3.2    Installments

     Sale_Month  Sale_Year  Cost_USD  Profit_USD  Profit_Margin
0            11       2025    7872.0      5248.0           40.0
1             2       2025    5470.2      3646.8           40.0
2             2       2025    6178.2      4118.8           40.0
3             6       2025   13908.0      9272.0           40.0
4             1       2025    1800.0      1200.0           40.0
..          ...        ...       ...         ...            ...
495           6       2025    2226.0      1484.0           40.0
496           7       2025    1987.2      1324.8           40.0
497           7       2025    3202.8      2135.2           40.0
498           6       2025     205.2       136.8           40.0
499           9       2025    3496.8      2331.2           40.0

[500 rows x 16 columns]

In [14]:
import numpy as np
customer_types = ["New", "Returning", "Wholesale", "Retail"]
marketing_channels = ["Email", "Social Media", "Direct", "Google Ads", "Referral"]
df["Customer_Type"] = np.random.choice(customer_types, size=len(df))
df["Marketing_Channel"] = np.random.choice(marketing_channels, size=len(df))

In [15]:
print(df)

     Sale_ID     Brand              Model    Country Storage   Color  \
0          1    Realme     Realme Model 2         UK   512GB    Gold
1          2      Vivo      Vivo Model 20  Australia   512GB    Blue
2          3  Motorola  Motorola Model 12    Germany   512GB   White
3          4      Vivo      Vivo Model 13        USA   512GB    Gold
4          5      Vivo      Vivo Model 15        UAE   128GB  Silver
..       ...       ...                ...        ...     ...     ...
495      496   OnePlus    OnePlus Model 5         UK   128GB    Blue
496      497    Xiaomi     Xiaomi Model 4     Canada   128GB    Gold
497      498      Vivo       Vivo Model 9   Pakistan   256GB    Blue
498      499   Samsung   Samsung Model 19     France   128GB    Gold
499      500    Xiaomi    Xiaomi Model 14         UK    64GB    Gold

     Price_USD  Units_Sold  Revenue_USD  Customer_Rating  Payment_Method  \
0          656          20        13120              3.7    Installments
1         1013           9         9117              3.7      Debit Card
2         1471           7        10297              3.1     Credit Card
3         1220          19        23180              3.6      Debit Card
4          375           8         3000              4.4  Online Payment
..         ...         ...          ...              ...             ...
495        371          10         3710              3.5      Debit Card
496        414           8         3312              5.0    Installments
497        314          17         5338              4.6            Cash
498        342           1          342              4.5            Cash
499       1457           4         5828              3.2    Installments

     Sale_Month  Sale_Year  Cost_USD  Profit_USD  Profit_Margin Customer_Type  \
0            11       2025    7872.0      5248.0           40.0           New
1             2       2025    5470.2      3646.8           40.0        Retail
2             2       2025    6178.2      4118.8           40.0     Returning
3             6       2025   13908.0      9272.0           40.0           New
4             1       2025    1800.0      1200.0           40.0     Wholesale
..          ...        ...       ...         ...            ...           ...
495           6       2025    2226.0      1484.0           40.0        Retail
496           7       2025    1987.2      1324.8           40.0        Retail
497           7       2025    3202.8      2135.2           40.0     Returning
498           6       2025     205.2       136.8           40.0     Wholesale
499           9       2025    3496.8      2331.2           40.0     Wholesale

    Marketing_Channel
0               Email
1              Direct
2          Google Ads
3          Google Ads
4            Referral
..                ...
495            Direct
496          Referral
497             Email
498        Google Ads
499            Direct

[500 rows x 18 columns]

In [16]:
df.to_csv("Clean_mobile_sales_data_2025.csv", index=False)

In [18]:
print(df)

     Sale_ID     Brand              Model    Country Storage   Color  \
0          1    Realme     Realme Model 2         UK   512GB    Gold
1          2      Vivo      Vivo Model 20  Australia   512GB    Blue
2          3  Motorola  Motorola Model 12    Germany   512GB   White
3          4      Vivo      Vivo Model 13        USA   512GB    Gold
4          5      Vivo      Vivo Model 15        UAE   128GB  Silver
..       ...       ...                ...        ...     ...     ...
495      496   OnePlus    OnePlus Model 5         UK   128GB    Blue
496      497    Xiaomi     Xiaomi Model 4     Canada   128GB    Gold
497      498      Vivo       Vivo Model 9   Pakistan   256GB    Blue
498      499   Samsung   Samsung Model 19     France   128GB    Gold
499      500    Xiaomi    Xiaomi Model 14         UK    64GB    Gold

     Price_USD  Units_Sold  Revenue_USD  Customer_Rating  Payment_Method  \
0          656          20        13120              3.7    Installments
1         1013           9         9117              3.7      Debit Card
2         1471           7        10297              3.1     Credit Card
3         1220          19        23180              3.6      Debit Card
4          375           8         3000              4.4  Online Payment
..         ...         ...          ...              ...             ...
495        371          10         3710              3.5      Debit Card
496        414           8         3312              5.0    Installments
497        314          17         5338              4.6            Cash
498        342           1          342              4.5            Cash
499       1457           4         5828              3.2    Installments

     Sale_Month  Sale_Year  Cost_USD  Profit_USD  Profit_Margin Customer_Type  \
0            11       2025    7872.0      5248.0           40.0           New
1             2       2025    5470.2      3646.8           40.0        Retail
2             2       2025    6178.2      4118.8           40.0     Returning
3             6       2025   13908.0      9272.0           40.0           New
4             1       2025    1800.0      1200.0           40.0     Wholesale
..          ...        ...       ...         ...            ...           ...
495           6       2025    2226.0      1484.0           40.0        Retail
496           7       2025    1987.2      1324.8           40.0        Retail
497           7       2025    3202.8      2135.2           40.0     Returning
498           6       2025     205.2       136.8           40.0     Wholesale
499           9       2025    3496.8      2331.2           40.0     Wholesale

    Marketing_Channel
0               Email
1              Direct
2          Google Ads
3          Google Ads
4            Referral
..                ...
495            Direct
496          Referral
497             Email
498        Google Ads
499            Direct

[500 rows x 18 columns]